### ISSUE TITLE
Set max value based on the greatest rater

### ISSUE THREAD

**Issue by NaturallyAsh** [Inconnu08/android-ratingreviews#7]
First of all, I just wanted to say that I have never used a library and it work so perfectly and flawlessly on my first attempt at implementing it.  For that, bless you sir.

I do have a feature request.  The ratings count data that I receive always varies and can be from as low as 50 ratings to as high as a couple of thousand.  It would be cool to have a way to allow the max value to be based on the greatest number among the raters instead of just setting to a specific value.  

Thank you again for hard work.

**Comment by Inconnu08** [comment]
Thank you so much for your feedback, @NaturallyAsh ! This means a lot! One of the goals of the library was to make it fast and easy to implement, I am glad it worked flawlessly for you. 😊

I am not sure if I understood your question properly. But you could simply get the greatest rater value from your code and set it as the max value on the constructor like this:

`ratingReviews.createRatingBars([your greatest rater value], BarLabels.STYPE1, colors, raters);`

If you're talking about setting `maxValue` of each bar separately? In that case, that cannot be changed individually at the moment.

I hope this solves your issue. If not let me know. 😊

**Comment by NaturallyAsh** [comment]
Aw man thank you! Yes that worked perfectly.  I do have one more question.  Does the rater work best with constraint layout?  I am using it in a coordinator layout but no matter what I do (match content, wrap content, or a specific width) the highest rater text gets cut off from the end.  Any suggestions?  Thank you.

**Comment by Inconnu08** [comment]
Assuming it all worked for you!
