### ISSUE TITLE
ERROR: Failed to resolve: com.github.Inconnu08:android-ratingreviews:1.2.0

### ISSUE THREAD

**Issue by Erraoudy** [Inconnu08/android-ratingreviews#9]
**Describe the bug**
`### ERROR: Failed to resolve: com.github.Inconnu08:android-ratingreviews:1.2.0
`

**Comment by Inconnu08** [comment]
Have you followed the installation procedure properly? 

[installation](https://github.com/Inconnu08/android-ratingreviews#installation)

I think you don't have `maven { url 'https://jitpack.io' }` In your module level `build.gradle`
